site_name: SimpleHome-Documentation
site_url: https://simple-home.github.io/documentation/
theme:
  name: material
  logo: https://raw.githubusercontent.com/Simple-Home/Simple-Home/master/public/images/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: light green
      primary: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: light green
      primary: light green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - codehilite